[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "ipxact-compiler"
dynamic = ["version"]
description = "Parses IEEE 1685-2022 IP-XACT XML into a Python object model."
readme = "README.md"
license = "LGPL-3.0-only"
license-files = ["LICENSE"]
authors = [
    { name = "Maxime Travaillard"},
]
requires-python = ">=3.9"
dependencies = [
    "lxml",
]
keywords = [
    "IP-XACT", "IEEE 1685", "XML", "Compiler",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Repository = "https://github.com/IP-XACT/ipxact-compiler"
Issues = "https://github.com/IP-XACT/ipxact-compiler/issues"

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.dynamic]
version = {attr = "ipxact.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ipxact = ["py.typed"]
